version: '3.8'

services:
  portfolio:
    image: ${PORTFOLIO_IMAGE:-ghcr.io/tolibme/portfolio:latest}
    ports:
      - "80:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped